config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  resources :articles do
    resources :comments, only: [:create]
    member do 
      post 'like'
    end
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'ss7', to: 'codes#index'
  resources :codes, except: [:index]
  resources :categories, except: [:destroy]
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end 

app/models/article.rb
class Article < ApplicationRecord
  
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :user_id, presence: true
  default_scope -> {order(updated_at: :desc)}
  validates :title, presence: true, length: {minimum: 5, maximum: 50}
  validates :description, presence: true, length: {minimum: 13, maximum: 1300}
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was saved successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show
    @comment = Comment.new
    @comments = @article.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
    
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was deleted successfully"
    redirect_to articles_path
  end
  
  def like
    like = Like.create(like: params[:like], user: current_user, article: @article)
    if like.valid?
      flash[:success] = "You've liked this article"
      redirect_to :back
    else
      flash[:warning] = "You can only like/dislike an article once"
      redirect_to :back
    end
  end
  

  
  private
  
    def set_article
       @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end
  
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:warning] = "You can edit or delete your own articles only"
      redirect_to root_path
    end
  end
  
  def require_user_like
    if !logged_in?
      flash[:warning] = "You must be logged in to perform that action"
      redirect_to :back
    end
end
  
end

app/views/articles/_articles.html.erb
<%obj.each do |article|%>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%=link_to article.title, article_path(article)%>
        </div>
        <div class="article-body">
          <%=truncate(article.description, length: 100)%>
          <div class="article-meta-details">
            <small>
              created by: <%= article.user.username.capitalize if article.user %>,
              <%=time_ago_in_words(article.created_at)%> ago,
              Last updated: <%=time_ago_in_words(article.updated_at)%> ago
               | <%=pluralize(article.comments.count, "Comment")%>
            </small>
          </div>
        </div>
        <%if article.categories.any?%>
          <p>
            Categories: <%=render article.categories%>
          </p>
        <%end%>
        <%if logged_in? && (current_user==article.user || current_user.admin)%>
          <div class="article-action">
            <%=link_to 'Edit', edit_article_path(article), class: "btn btn-xs btn-primary"%>
            <%=link_to 'Delete', article_path(article), method: :delete,
            data: {confirm: "Are you sure to delete this Article?"}, class: "btn btn-xs btn-danger"%>
          </div>
        <%end%>
        
        <div class="row">
          <div class="pull-right liking">
            <%= link_to like_article_path(article, like: true), method: :post do %>
              <i class="glyphicon glyphicon-thumbs-up"></i> 
            <% end %> <%= article.thumbs_up_total %> || 
            <%= link_to like_article_path(article, like: false), method: :post do %>
              <i class="glyphicon glyphicon-thumbs-down"></i>
            <% end %> <%= article.thumbs_down_total %>
          </div>
        </div>
        
      </div>
    </div>
  </div>
<%end%>

app/views/articles/_form.html.erb
<%=render 'shared/errors', obj: @article%>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of the article", autofocus: true%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :description,rows: 13, class: "form-control", placeholder: "Body of the article", autofocus: true%>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%=f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
              <%cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text}%>
            <%end%>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <%end%>
    <div class="col-xs-4 col-xs-offset-4">
      <%=link_to "(Cancel the request and return to Article's page)", articles_path%>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Update this Article</h1>

<%=render 'form'%>

app/views/articles/index.html.erb
<h1 align="center">Listing all the articles</h1>

<div align="center">
  <%=will_paginate%>
</div>
<%=render 'articles', obj: @articles%>
<div align="center">
  <%=will_paginate%>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Create an Article</h1>

<%=render 'form'%>

app/views/articles/show.html.erb
<h2 align="center">Title: <%=@article.title%></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <%if @article.user%>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>created by:</li>
          <li><%=link_to gravatar_for(@article.user), user_path(@article.user)%></li>
          <li class="article-title">
            <%=link_to @article.user.username.capitalize, user_path(@article.user)%>
          </li>
          <li><small><%=pluralize(@article.user.articles.count, "article") if @article.user.articles%></small></li>
        </div>
      </div>
    </ul>
  <%end%>  
  <h4 class="center description"><strong>Description:</strong></h4>
  <%=simple_format(@article.description)%>
  <div class="row">
    <div class="col-md-12">
      Created: <%= time_ago_in_words(@article.created_at) %> ago and Last updated was : <%= time_ago_in_words(@article.updated_at) %> ago!
    </div>
  </div>
  <%if @article.categories.any?%>
    <p>Categories: <%= render @article.categories%></p>
  <%end%>
  <div class="article-action">
    <%if logged_in? && (current_user==@article.user || current_user.admin?)%>
      <%=link_to 'Edit this Article', edit_article_path(@article), class: "btn btn-xs btn-primary"%>
      <%=link_to "Delete this Article", article_path(@article), method: :delete,
      data: {confirm: "Are you sure to delete this Article?"}, class: "btn btn-xs btn-danger"%>
    <%end%>
    <%=link_to "View all Articles", articles_path, class: "btn btn-xs btn-success"%>
  </div>
</div>

<div class="row liking">
  <div class="row col-md-8 col-md-offset-2">
    <%= link_to like_article_path(@article, like: true), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-up"></i> 
    <% end %> <%= @article.thumbs_up_total %> ||
    <%= link_to like_article_path(@article, like: false), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-down"></i> 
    <% end %><%= @article.thumbs_down_total %>
  </div>
</div>

<% if logged_in? %>
  <div class='row'>
    <div class='col-md-10'>
      <hr/>
      <%= form_for([@article, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-md-8 col-md-offset-3">
            <%= f.text_area :description,rows: 8, class: "form-control", placeholder: "Enter comment", autofocus: true%>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-3 col-md-10">
            <%= f.submit "Create comment", class: 'btn btn-success btn-lg' %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
<%end%>

<%if @article.comments.count != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <div id="messages">
        <%=render partial: 'comments/comments', object: @comments%>
      </div>
    </div>
  </div>
<%else%>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>
        No comments yet!
      </h3>
    </div>
  </div>
<%end%>